# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2796ed1dd6076a1e7912b146361c8675180c04f4ae9bc15d5b3e119e28b2024514fa51debd61eeae4ff5cbb069af97781fc8bcae4b14dc98e474e362cf5f485a

test:
  secret_key_base: 2965eb6e1dd934c10cd671184b2395708556bdd590475417610ac4936f0919cc81a13ce7a9fcc0dcc0772d4983ce3414f10637ef1ed347bcd9e95d0291b35014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
